server:
  port: 8086
  servlet:
    context-path: /movie/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3301/movie
    username: usuarioAplicacao
    password: 123456789Tu
